<?php
/**
 * @var \Inchoo\Ticket\Block\Detail $block
 */
if (!$block->getTicketDetails()->getStatus()) : ?>
    <hr />
    <div>
        <form action="<?= $block->escapeUrl($block->getPostUrl()) ?>" method="post"
              data-mage-init='{"validation":{}}'>
            <label for="content" class="label"><?= $block->escapeHtml(__('Message')); ?></label>
            <textarea data-validate='{"required":true}' name="content" id="content" type="text"></textarea>
            <input name="id" type="hidden"
                   value="<?= $block->escapeHtml($block->getTicketDetails()->getId()) ?>"><br /><br />
            <input type="submit" class="action submit primary" value="<?= $block->escapeHtml(__('Reply'))?>">
        </form>
    </div>
<?php endif; ?>
