<?php
/**
 * @var \Inchoo\Ticket\Block\Detail $block
 */
?>
<?php if (!$block->getTicketDetails()->getStatus()): ?>
    <hr />
    <div>
        <form action="<?php echo $block->escapeUrl($block->getPostUrl()) ?>" method="post" data-mage-init='{"validation":{}}'>
            <label for="content" class="label"><?php echo __('Message'); ?></label>
            <textarea data-validate='{"required":true}' name="content" id="content" type="text"></textarea>
            <input name="id" type="hidden" value="<?= $block->escapeHtml($block->getTicketDetails()->getId()) ?>"><br /><br />
            <input type="submit" class="action submit primary" value="<?php echo __('Reply')?>">
        </form>
    </div>
<?php endif ?>