<?php
/**
 * @var \Inchoo\Ticket\Block\Ticket $block
 * @var $ticket \Inchoo\Ticket\Api\Data\TicketInterface
 */
?>
<div>
    <div>
        <h3>Create ticket</h3>
        <form action="<?= $block->escapeUrl($block->getPostUrl()) ?>" method="post" data-mage-init='{"validation":{}}'>
           <label for="title" class="label"><?= __('Subject'); ?></label>
            <input data-validate='{"required":true, maxlength:254}' name="title" id="title" type="text"><br /><br />
            <label for="content" class="label"><?= __('Message'); ?></label>
            <textarea data-validate='{"required":true}' name="content" id="content" type="text"></textarea><br /><br />
            <input type="submit" class="action submit primary" value="<?= __('Submit')?>">
        </form>
    </div><br /><br />
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif;
    if ($block->getTicketCollection()->getSize() > 0):?>
        <div class="table-wrapper orders-history">
            <table class="table">
                <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Created at</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($block->getTicketCollection() as $ticket): ?>
                        <tr>
                            <td>
                                <a href="<?= $block->escapeUrl($block->getTicketDetailsUrl($ticket->getId())); ?>">
                                   <?= $block->escapeHtml($ticket->getSubject()); ?>
                                </a>
                            </td>
                            <td><?= $block->escapeHtml($block->formatDateForPhtml($block->getCreatedAt())); ?>
                            </td>
                            <td><?php
                                if (!$ticket->getStatus()):
                                    ?>
                                    <a href="<?= $block->escapeUrl($block->getCloseUrl($ticket->getId())); ?>" class="action submit primary"><?= __('Close'); ?></a><?php
                                elseif ($ticket->getStatus()):
                                    echo __('Closed');
                                endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>
