<?php
/**
 * @var \Inchoo\Ticket\Block\Detail $block
 * @var \Inchoo\Ticket\Api\Data\TicketReplyInterface $reply
 */
?>
<hr />
<div class="col">
    <p><?php echo $block->escapeHtml(__('Replies')); ?>:</p>
    <?php foreach ($block->getReplies() as $reply) :?>
        <div style="text-align:<?php
        if ($reply->getAdminId()) :
            echo 'right';
        else :
            echo 'left';
        endif;?>
        ">
            <p><?php echo $block->escapeHtml($block->formatDateForPhtml($block->getCreationTime())) . ' ';
            if ($reply->getAdminId() !== null) :
                echo $block->escapeHtml($block->getAdminName($reply->getAdminId())) . ':';
            else :
                echo $block->escapeHtml($block->getCustomerName($block->getTicketDetails()->getCustomerId())) . ':';
            endif; ?>
            </p>
            <p><?php echo $block->escapeHtml($reply->getMessage()); ?></>
        </div><br />
    <?php endforeach; ?>
</div>