<?php
/**
 * @var \Inchoo\Ticket\Block\Detail $block
 * @var \Inchoo\Ticket\Api\Data\TicketReplyInterface $reply
 */
?>
<div class="columns">
    <div id="ticketDetail">
        <h2>
            <?php echo __('Ticket title'); ?>: <?= $block->escapeHtml($block->getTicketDetails()->getSubject()); ?>
        </h2>
        <h3>
            <?php echo __('Ticket content'); ?>: <?= $block->escapeHtml($block->getTicketDetails()->getMessage()); ?>
        </h3>
    </div>
    <hr />
    <div>
        <p><?php echo __('Replies'); ?>:</p>
        <?php foreach ($block->getReplies() as $reply): ?>
            <p><?php
                echo $block->formatDate(
                        $block->escapeHtml($reply->getCreatedAt()),
                        3,
                        true,
                        'Europe/Zagreb'
                    ) . ' ';
                if ($reply->getAdminId() !== null) {
                    echo $block->escapeHtml($block->getAdminName($reply->getAdminId()));
                } else {
                    echo $block->escapeHtml($block->getCustomerName()) . ':';
                }?>
            </p>
            <p><?= $block->escapeHtml($reply->getMessage()); ?></p><br />
        <?php endforeach; ?>
    </div>
</div>

