<?php
/**
 * @var \Inchoo\Ticket\Block\Ticket $block
 * @var $ticket \Inchoo\Ticket\Api\Data\TicketInterface
 */
?>
<div>
    <div>
        <h3>Create ticket</h3>
        <form action="<?php echo $block->escapeUrl($block->getPostUrl()) ?>" method="post" data-mage-init='{"validation":{}}'>
           <label for="title" class="label"><?php echo __('Subject'); ?></label>
            <input data-validate='{"required":true, maxlength:254}' name="title" id="title" type="text"><br /><br />
            <label for="content" class="label"><?php echo __('Message'); ?></label>
            <input data-validate='{"required":true}' name="content" id="content" type="text"><br /><br />
            <input type="submit" class="action submit primary" value="<?php echo __('Submit')?>">
        </form>
    </div><br /><br />
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif;
    if ($block->getTicketCollection()->count() > 0):?>
        <div class="table-wrapper orders-history">
            <table class="table">
                <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Created at</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($block->getTicketCollection() as $ticket): ?>
                        <tr>
                            <td>
                                <a href="<?php echo $block->escapeUrl($block->getTicketDetailsUrl($ticket->getId())); ?>">
                                   <?= $block->escapeHtml($ticket->getSubject()); ?>
                                </a>
                            </td>
                            <td><?php
                                echo $block->formatDate(
                                    $block->escapeHtml($block->getCreatedAt()),
                                    3,
                                    true,
                                    'Europe/Zagreb'
                                )?>
                            </td>
                            <td><?php
                                if ((bool)$ticket->getStatus() === false) {
                                    ?>
                                    <a href="<?php echo $block->escapeUrl($block->getCloseUrl($ticket->getId())); ?>" class="action submit primary"><?php echo __('Close'); ?></a><?php
                                } elseif ((bool)$ticket->getStatus() === true) {
                                    echo __('Closed');
                                }?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>
